### ISSUE TITLE
Introduction clarification of the motivation 

### ISSUE THREAD

**Issue by mglt** [ietf-homenet-wg/ietf-homenet-hna#15]
The risk of DDoS by having the CPE seems unclear or at least at the wrong place as we have already stated that the CPE is managing the naming of the home network.

OLD:
  CPEs, Homenet Naming Authority, as well as home network devices are
   usually low powered devices not designed not for terminating heavy
   traffic.  As a result, hosting an authoritative DNS service visible
   to the Internet may expose the home network to resource exhaustion
   and other attacks.  Additionally, the names become unavailable during
   disruptions.

   In order to avoid resource exhaustion and other attacks, this
   document describes an architecture that outsources the authoritative
   naming service of the home network.  More specifically, the Homenet
   Naming Authority builds the Homenet Zone and outsources it to an
   Outsourcing Infrastructure.  The Outsourcing Infrastructure in in
   charge of publishing the corresponding Public Homenet Zone on the
   Internet.  This is done using standard DNS mechanisms involving
   primary and secondary DNS servers, with the HMA hosted primary being
   a stealth primary.

**Comment by v6ops** [comment]
There is a big difference between "managing the content of a zone" and "providing name resolution exposed to the entire public Internet".
