### ISSUE TITLE
move section 4.2 (example) to an appendix

### ISSUE THREAD

**Issue by mcr** [ietf-homenet-wg/ietf-homenet-hna#2]

**Comment by mcr** [comment]
The choices of IPsec or TLS for security (vs DNSSEC) should go into the Security Considerations section, not to confuse implementers.

**Comment by mglt** [comment]
I believe the comment is based on section 4.3. The Security Consideration describes TSIG TLS, IPsec so I do not think anything should be added to the Security Consideration. I do not think section 4.3 goes too far into the description. I am tempt to think that removing DNSSEC, TLS, TSIG will be confusing, so we need to check if further actions are needed.

**Comment by mcr** [comment]
I think that I've done this.
