### ISSUE TITLE
Securing Synchronization

### ISSUE THREAD

**Issue by mglt** [ietf-homenet-wg/ietf-homenet-hna#22]
I am wondering if TSIG is the right way to do. 

IPsec/TLS provide confidentiality in addition to TSIG and do not use PSK. 

TSIG / IPsec would be easier to implement as no integration is required.

**Comment by v6ops** [comment]
My experiments so far indicate that DNS over TLS RFC 7858 is relatively easy to implement using a combination of the ldns lib from NLnet Labs + openssl.

The hard part is the obscurity of the openssl API, but once you have that running there is a lot of upside: privacy, avoidance of replay attacks, authentication of the the DM to the HNA, plus optionally authentication of the HNA to the DM.

I think the text currently discourages DNS over TLS, whereas my felling is that we should be recommending it.

It's a lot better than the alternatives IMHO.

**Comment by mcr** [comment]
TLS works, so we are going to stick with it.
Needs text edits to make this the preferred.
