### ISSUE TITLE
Reverse terminology

### ISSUE THREAD

**Issue by mglt** [ietf-homenet-wg/ietf-homenet-hna#23]
I am wondering if we need that terminology. I would rather bind the different zones to the one we already defined for the forwarding DNS.

**Comment by mcr** [comment]
please explain more.  Are you saying that you want the reverse zone to be published as part of the forward, and the pointed to by DNAME or something like that?    I think that we do need to talk more about how the reverse zone is managed, as it has a different relationship to it's parent than the forward zone.

**Comment by mcr** [comment]
* Homenet Reverse Zone: The reverse zone file associated with the Public
Homenet Zone.

**Comment by mcr** [comment]
Duplicate of #17.
