### ISSUE TITLE
should public zone allow ULAs

### ISSUE THREAD

**Issue by mcr** [ietf-homenet-wg/ietf-homenet-hna#28]
We write:

```
Resource records associated with services or devices that are not
expected to be resolvable from outside the home network, or resource
records bound to non-globally reachable IP addresses e.g. ULA, MUST NOT
be part of the Public Homenet Zone.
```

But, I think that the case where the user has a VPN to their home, and they would like the VPN to be kicked when a ULA is accessed would want to have a public name pointing at a "private" IPv6 address.

**Comment by mglt** [comment]
When the VPN is set, I would consider the VPN client as part of the home network, so the use of ULA is  provisioned as a trigger to "force" communications to be private. Well in other words, I do not see the example as contradicting the statement. Maybe the scenario you describe could be mentioned for clarifying the purpose.

**Comment by mcr** [comment]
Removed.
