### ISSUE TITLE
What term to use for the synchronization server

### ISSUE THREAD

**Issue by mcr** [ietf-homenet-wg/ietf-homenet-hna#3]
some use "distribution server", what do others use?
Ask dnsops.

**Comment by mglt** [comment]
The respopnse I receievd from RSO was Distributed master.

**Comment by v6ops** [comment]
Distribution Master (DM)

As discussed in the meeting 24th May.

**Comment by v6ops** [comment]
I've updated the text version to replace "Synchronisation Server" with "Distribution Master" and aligned throughout the document (including ascii diagram).
