### ISSUE TITLE
HNA provisioning --- what is needed for forward zone provisioning

### ISSUE THREAD

**Issue by mcr** [ietf-homenet-wg/ietf-homenet-hna#39]
Maybe hna-proviisonning may be put in the appendix.

**Comment by v6ops** [comment]
My implementation uses a son file for provisioning:

A notify address to send notify messages to the DM (although that could also be via the control channel)
a DM-ACL to inform the HNA from where to expect the AXFR, so the HNA can add an ACL in the knot config file.
dm_ctrl: the address or name of the control channel destination.
dm_port: where the DM is listening
zone: the name of the delegated Homenet zone
hna_certicate: the cert used to authenticate the HNA to the DM


ray@raspberrypi:~/homenet_dm/src $ more homenet_hna_client_config.json
{"dm_notify":"2001:470:1f15:62e:21c::2","dm_acl":"2001:470:1f15:62e:21c::/64","d
m_ctrl":"192.168.1.18","dm_port":"4433","zone":"daniel.homenetdns.com","hna_cert
ificate":"-----BEGIN CERTIFICATE-----\nMIIDTjCCAjYCFGy+Htuv9ErWhDkwvFU8mzocStmaM
A0GCSqGSIb3DQEBCwUAMIGm\nMQswCQYDVQQGEwJOTDEWMBQGA1UECBMNTm9vcmQgQnJhYmFudDESMBA
GA1UEBxMJ\nRWluZGhvdmVuMRMwEQYDVQQKEwpIb21lbmV0IFdHMRkwFwYDVQQLExBIb21lbmV0\nIEh
OQSBEZW1vMRowGAYDVQQDExFkbS5ob21lbmV0ZG5zLmNvbTEfMB0GCSqGSIb3\nDQEJARYQdHJhc2hAZ
2xvYmlzLm5ldDAeFw0xOTA5MDYxNTEzNTVaFw0yNDA5MDQx\nNTEzNTVaMCAxHjAcBgNVBAMTFWRhbml
lbC5ob21lbmV0ZG5zLmNvbTCCASIwDQYJ\nKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKaW3w7RUydoY
vWZpqe06jK95KBF4TTu\n/4pub/Asf9Hi3tq1FoOYn5g9ISASI53qlIv+w9gmVF0x233MNRSkk/OkynO
/YTbn\nGH98fSym6oMK2S1z5yWW6MYCpnZLSV+EN6194xJNbNgvKNlOZgkHXuBJ4Nh1m3/f\nCItWGuI
Wx2KN5ZsLPnmpFGOTCgEQvTwJf374dfplaJ2tTivl661zC+WpqfqVmrkN\nAeStzhBSMduwyi6kxKCl3
b/wrXkwYX65tOUbLVm3m9xDmjvgwXJPIo2Asbd5idAH\na/LAGLE2iLNa1Y3iE6J6JQELgccBpqJBH3w
tBmsozAcClg1EbxbJ0KMCAwEAATAN\nBgkqhkiG9w0BAQsFAAOCAQEAU2FgncCZgB7l7KL8IAiFoPfu3
IKDiRau1l1waIW8\nYPgFyjRAr5iDF+PDjPufj/lpELL35IKk4W6weAaYWnbkjImKj6Mv8zKq11wh7WN
I\nOlSg1fYCZvHHcED+AEmH3CqIH5ZPO+2juwh+Gf8X0Sg2TpnPmiNttbJZ6kAOUIj8\nVwIUvESJF0B
0Pb3K+nPKNOmMtmYYMwTBVH797wUFgNOXx4rxI1idt95h141KVwmv\nd8UtPE3tLld59tLBxnaK8zhMk
lpw6cAcz6xk8AlQJ/TK/dP519hl2Nl+54FM3+XQ\nINONB7izurX3Ws7yDI6TmmPm9I/h4ZTf906FG70
RKD/AGA==\n-----END CERTIFICATE-----\n","hna_key":"-----BEGIN RSA PRIVATE KEY---
--\nMIIEowIBAAKCAQEAppbfDtFTJ2hi9Zmmp7TqMr3koEXhNO7/im5v8Cx/0eLe2rUW\ng5ifmD0hIB
IjneqUi/7D2CZUXTHbfcw1FKST86TKc79hNucYf3x9LKbqgwrZLXPn\nJZboxgKmdktJX4Q3rX3jEk1s
2C8o2U5mCQde4Eng2HWbf98Ii1Ya4hbHYo3lmws+\neakUY5MKARC9PAl/fvh1+mVona1OK+XrrXML5a
mp+pWauQ0B5K3OEFIx27DKLqTE\noKXdv/CteTBhfrm05RstWbeb3EOaO+DBck8ijYCxt3mJ0Adr8sAY
sTaIs1rVjeIT\nonolAQuBxwGmokEffC0GayjMBwKWDURvFsnQowIDAQABAoIBAEKMGmcM767aYE3E\n
J3LvLm8+tEniIGjI4IQoQccrv5PUkTnFBU1kdryWDtmE5X177ANQrmN2TFU+SXQj\nU0D/zaqStd0vIm
KQRpUG4eooc54Ng1xI5Jl7g1k2TdELmi/x3VwM4dy52TUzAZpt\nWw1YSGpImO1fbdLTAdLHfs26U8Pm
Tgi73E0HKd+oE4K0FesXAFa9yUpCy2AlNJ/9\nFUTiekAfzDBLyus9wBHPokK/EeRlLnsCCKwJ4y3A3n
kCjIjaq5OjOG08h/oEbg7k\ng80tetBQb9mv3RDOp7Rkz2UBkffl6BzijW0NI40EbVtel5gXODNfNVUd
5VDFHKa7\nLhYvKGECgYEA2iv4o+d21YQRZ0Mmh9Y5RybtoaOQnQcZlEafoQ2J6e9deA0TpMhD\nf549
DT3C4Z4zyWE0XAaN8LYbT8keEXndbIyjv+9Dk7EzF/f9IXepy7Py8om2BOWu\ntt/yRwzkYAAOFfCPAV
510eebVqSbDxNIwkdUHC5CPrNiL/X3l48mLkUCgYEAw3lN\nTbQm/dabxZqtYWio4I4xtVJLDznzKAdJ
copmikDUHM4te4YT/QTFbxcnB5xtNk7w\noHmuo6ARt2WCteqVcXiDMzXB705XV99XaiRUI5fZjDtWy4
JiexOy1RrxmNNLz0Wa\n8KG1YxNqMzGd1LTOCkKA+u+yi8Zw5pTbcWPqhccCgYBsuYULiYo7FbnmkBxf
jW61\n+rxp1S14U9V3g0qB5FFad6NI9JtZf0PEEYOzWZgI/+Im9X42bj3GO7qYpE2LwAOM\n2Pmx6Pbw
X1prE3beetfvYBourFo9ToknMat3pQEapmxemqdpsz1cAePz5cwwUxfr\nWcic0qDIxnSkGhvtN7V7UQ
KBgQCxRtWg3v1twLBNKdaMPQrLfKoAM7329Stc5h7q\nTjJouBqmdSYynIqMMUONWIYBFRDG7Bi2sSR9
KLJojRtaOIGIAy+Zxes4SOhVvSve\nC0xza0fVMgupTXpa/KZ3NpRdcWOTeyDlkwKZ9AWgoCLvwXoLO/
0Vl0VqFnJV7DKI\nR4FuCQKBgGakgWdwa4mLLEO1HTXB6wRVI/PKeodVxmOiOe/7GYajJ7fWEo++QnKJ
\nc/tr/pvWhDV+TK1yxS9MYKAj1v/6n92hJy2UknkWb2tT1xTNLZbIPEwFNwKJ1fPl\ntCu27yFntoAR
SvNef0MBkk+qncTgTk1Erm1xarsQGUuWPq11vGD7\n-----END RSA PRIVATE KEY-----\n"}

**Comment by mcr** [comment]
Added this as a section.
