### ISSUE TITLE
what to call the Homenet server

### ISSUE THREAD

**Issue by mcr** [ietf-homenet-wg/ietf-homenet-hna#4]
Possible terms are:
Hidden primary vs Stealth Primary and maybe other terms.

**Comment by mglt** [comment]
I asked Root Server Operators and they designates the server retrieving the root zone from the Root Zone Maintainer as Distribution Masters. 

Note this is a secondary. But on an RSO perspective the Distributed Master provide the input to the multiple instances of root servers. 

Note that Master should at least be replaced by Primary in our case.

**Comment by mcr** [comment]
HNA                       = is the Homenet's Stealth Primary.
Distribution Master = Infrastructure's Stealth Secondary, and it has many public secondaries.
