### ISSUE TITLE
section 6.1, outsources zone signing

### ISSUE THREAD

**Issue by mcr** [ietf-homenet-wg/ietf-homenet-hna#6]
Remove option to sign by outsourcing entity.
Does anyone actually want to do this?

**Comment by mglt** [comment]
The section has been removed. However, I believe the original idea was to have a public zone that differs from the homenet zone. I believe we are now pushing for having the exact same zone being sevred. We should check if that is clear and if the document is coherent with that.

**Comment by mcr** [comment]
What is the "homenet zone"?
If it is home.arpa, then yes, it might well be different.

**Comment by mglt** [comment]
Please let me know if my understanding is correct:
- the Homenet Zone designates the FQDN to IP (mapping my-nas.my-homnet.com). This one is signed by the HNA
- The  Homenet Reverse Zone is signed by a third party, which is the ISP. I am a bit unclear if we should go for a MAY be signed versus a SHOULD/MUST be signed by the ISP. It is also unclear why the ISP is more likely to sign them versus proceeding to a delegation.

**Comment by mcr** [comment]
I agree with point one, but I feel that I might be missing some less obvious point.  It is signed by the HNA.
Why would the reverse zone be different than the forward zone?  The clear distinction is that the reverse zone can only be delegated from the ISP, and the credentials to update things should be in DHCPv6.

**Comment by mglt** [comment]
That was my point. I do not see why the reverse zone should be considered differently. I thought that what you suggested previously. I understand that we agree there is no difference to that respect. 

I understand you suggest to say that the HNA is signing the zone. The current text says. I am wondering if that addresses your concern ?
This document RECOMMENDS that signing is performed by the
HNA and that the Public Homenet Zone is outsourced signed.

**Comment by mcr** [comment]
All agreement.
