### ISSUE TITLE
what about internal-only names?

### ISSUE THREAD

**Issue by mcr** [ietf-homenet-wg/ietf-homenet-hna#8]
home.arpa should be used for internal names.

**Comment by v6ops** [comment]
Suggest: "Internal-only names are out of scope for this draft"


See https://www.ietf.org/archive/id/draft-ietf-homenet-simple-naming-03.txt

Homenet Domain  A domain name that is used for publishing the names of devices and services that are present on the homenet.  By default, 'home.arpa.'

**Comment by mcr** [comment]
* Homenet Zone: is the DNS zone for use within the boundaries of the
home network: home.arpa, see {{!RFC8375}}). This zone is not considered
public and is out of scope for this document.
